// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeU0bbG1vAroPyo8JWeFVAqah49J0BzU',
    appId: '1:953811389981:web:53407ee1144d5ab6ec00f4',
    messagingSenderId: '953811389981',
    projectId: 'iit-flutter-projecgt',
    authDomain: 'iit-flutter-projecgt.firebaseapp.com',
    storageBucket: 'iit-flutter-projecgt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0g-Cc2TO79m670hadKa5YfwxpQGI1JyA',
    appId: '1:953811389981:android:2c4fd9004720766bec00f4',
    messagingSenderId: '953811389981',
    projectId: 'iit-flutter-projecgt',
    storageBucket: 'iit-flutter-projecgt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRyOTqPfMShxftjjb1RB8_Jad3dXQj8A',
    appId: '1:953811389981:ios:c6c411df181fa6c2ec00f4',
    messagingSenderId: '953811389981',
    projectId: 'iit-flutter-projecgt',
    storageBucket: 'iit-flutter-projecgt.appspot.com',
    androidClientId: '953811389981-f0e653sdon18j6cgrpcipdgv7q8hve04.apps.googleusercontent.com',
    iosClientId: '953811389981-bjle789afodr8smkntsc5l70ntk96b55.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRyOTqPfMShxftjjb1RB8_Jad3dXQj8A',
    appId: '1:953811389981:ios:c6c411df181fa6c2ec00f4',
    messagingSenderId: '953811389981',
    projectId: 'iit-flutter-projecgt',
    storageBucket: 'iit-flutter-projecgt.appspot.com',
    androidClientId: '953811389981-f0e653sdon18j6cgrpcipdgv7q8hve04.apps.googleusercontent.com',
    iosClientId: '953811389981-bjle789afodr8smkntsc5l70ntk96b55.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeU0bbG1vAroPyo8JWeFVAqah49J0BzU',
    appId: '1:953811389981:web:3bf19321ab377175ec00f4',
    messagingSenderId: '953811389981',
    projectId: 'iit-flutter-projecgt',
    authDomain: 'iit-flutter-projecgt.firebaseapp.com',
    storageBucket: 'iit-flutter-projecgt.appspot.com',
  );
}
