// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4skRlPXoZBR_vPw0pAQu_sKGN2-oJp8M',
    appId: '1:191086498053:web:7b10c1068ca3bdc8e4e76c',
    messagingSenderId: '191086498053',
    projectId: 'iit-flutter-app',
    authDomain: 'iit-flutter-app.firebaseapp.com',
    storageBucket: 'iit-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_C6Fj68QqpJjWa38F7PMUN_a6HReFmXQ',
    appId: '1:191086498053:android:d5b7258d37299ffce4e76c',
    messagingSenderId: '191086498053',
    projectId: 'iit-flutter-app',
    storageBucket: 'iit-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyActA38iizrKnkf0e1xA2CbCmmmXAA24N8',
    appId: '1:191086498053:ios:6495add4eecbb910e4e76c',
    messagingSenderId: '191086498053',
    projectId: 'iit-flutter-app',
    storageBucket: 'iit-flutter-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyActA38iizrKnkf0e1xA2CbCmmmXAA24N8',
    appId: '1:191086498053:ios:6495add4eecbb910e4e76c',
    messagingSenderId: '191086498053',
    projectId: 'iit-flutter-app',
    storageBucket: 'iit-flutter-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4skRlPXoZBR_vPw0pAQu_sKGN2-oJp8M',
    appId: '1:191086498053:web:3f2f526f5886531be4e76c',
    messagingSenderId: '191086498053',
    projectId: 'iit-flutter-app',
    authDomain: 'iit-flutter-app.firebaseapp.com',
    storageBucket: 'iit-flutter-app.appspot.com',
  );

}